logger:
  level: "local"  # local | dev | prod
server:
  port: "localhost"
  host: "8082"
  timeout: 4s #время на чтение запроса
  idle_timeout: 60s #время жизни соендинения(переиспользуем соендинение с одним клиентом)
storage:
  storageType: "sql" # sql || memory
  memory:
    path: "../../storage/storage.go"
  postgres:
    url: "postgres://alex:alex@localhost:5432/postgres"



