version: "3.8"
services:
#  calendar:
#    build: ./
#    command: ./calendar
#    ports:
#      - "8000:8000"
#    depends_on:
#       - postgres
  postgres:
    image: postgres:15.6
    environment:
      POSTGRES_DB: "calendardb"
      POSTGRES_USER: "alex"
      POSTGRES_PASSWORD: "alex"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"